force-app/main/default/objects/Batch_Flow__c/Batch_Flow__c.object-meta.xml
<CustomObject>
    <label>Batch Flow</label>
    <nameField>
        <label>Batch Flow Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Flows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Flow__c/fields/AsyncApexJobId__c.field-meta.xml
<CustomField>
    <fullName>AsyncApexJobId__c</fullName>
    <label>AsyncApexJobId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Batch_Flow__c/fields/Day_of_Month__c.field-meta.xml
<CustomField>
    <fullName>Day_of_Month__c</fullName>
    <label>Day of Month</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Batch_Flow__c/fields/Next_Job__c.field-meta.xml
<CustomField>
    <fullName>Next_Job__c</fullName>
    <label>Next Job</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Batch_Flow__c/fields/Next_Jobs__c.field-meta.xml
<CustomField>
    <fullName>Next_Jobs__c</fullName>
    <label>Next Jobs</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Batch_Flow__c/fields/Next_Scheduled_Run__c.field-meta.xml
<CustomField>
    <fullName>Next_Scheduled_Run__c</fullName>
    <label>Next Scheduled Run</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Batch_Flow__c/fields/Preferred_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Start_Time__c</fullName>
    <label>Preferred Start Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Batch_Flow__c/fields/Preferred_Start_Time_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Start_Time_Minutes__c</fullName>
    <label>Preferred Start Time Minutes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Batch_Flow__c/fields/Run_Units__c.field-meta.xml
<CustomField>
    <fullName>Run_Units__c</fullName>
    <label>Run Units</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Batch_Flow__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Batch_Flow__c/fields/Un_Scheduled__c.field-meta.xml
<CustomField>
    <fullName>Un_Scheduled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Un Scheduled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BatchFlowTriggerHandler.cls
public with sharing class BatchFlowTriggerHandler extends TriggerHandler {
    protected override void beforeUpdate() {
        processBatchJobsForExecution();
    }
    protected override void beforeInsert() {
        processBatchJobsForExecution();
    }

    private static void processBatchJobsForExecution() {

        List<Batch_Flow__c> executeJobs = new List<Batch_Flow__c>();
        Set<String> updateUnscheduledNextJobIds = new Set<String>();

        for(Batch_Flow__c job : (List<Batch_Flow__c>)Trigger.new) {

            if(Trigger.isUpdate) {

                Batch_Flow__c newJob = (Batch_Flow__c)job;
                Batch_Flow__c oldJob = (Batch_Flow__c)Trigger.oldMap.get(job.Id);

                // Check if jobs are waiting to be executed, if yes then execute jobs
                if(newJob.AsyncApexJobId__c == null &&
                   (newJob.Status__c == 'Queued' && oldJob.Status__c != 'Queued') ||
                   (newJob.Status__c == 'Failed' && oldJob.Status__c != 'Failed')) {

                    executeJobs.add(newJob);
                }

                // check if any scheduled fields have been changed
                // if so then re calculate the next scheduled run date
                if(oldJob.Preferred_Start_Time__c != newJob.Preferred_Start_Time__c ||
                   oldJob.Preferred_Start_Time_Minutes__c != newJob.Preferred_Start_Time_Minutes__c ||
                   oldJob.Day_of_Month__c != newJob.Day_of_Month__c ||
                   oldJob.Run_Units__c != newJob.Run_Units__c) {

                    newJob.Next_Scheduled_Run__c = BatchFlow.GetNextRunTimeForJob(newJob);
                }


                // if Next_Job__c field value is removed then set the 
                // unscheduled checkbox to false on the old next job field value
                //Deprecated
                //if(oldJob.Next_Job__c != null && newJob.Next_Job__c == null) {
                //    updateUnscheduledNextJobIds.add(oldJob.Next_Job__c);
                //}
                

                // if Next_Jobs__c field value is removed then set the 
                // TODO: need to bulkfiy this to evaluate each individual job
                // unscheduled checkbox to false on the old next job field value
                if(oldJob.Next_Jobs__c != null && newJob.Next_Jobs__c == null) {
                    updateUnscheduledNextJobIds.addAll(oldJob.Next_Jobs__c.split(','));
                }
            }
            else if(Trigger.isInsert) {

                Batch_Flow__c newJob = (Batch_Flow__c)job;

                // Set Next Scheduled Run for first time
                newJob.Next_Scheduled_Run__c = BatchFlow.GetNextRunTimeForJob(newJob);
            }
        }

        if(!executeJobs.isEmpty()) {
            BatchFlow.ExecuteJobs(executeJobs);
        }

        if(!updateUnscheduledNextJobIds.isEmpty()) {
            updateUnScheduledJobs(updateUnscheduledNextJobIds);
        }
    }
    // set the unscheduled checkbox to false on the old next job field value
    private static void updateUnScheduledJobs(Set<String> jobIds) {

        List<Batch_Flow__c> updateJobs = new List<Batch_Flow__c>();

        for(Batch_Flow__c job : [SELECT Id, Un_Scheduled__c
                                    FROM Batch_Flow__c
                                    WHERE Id IN :jobIds]) {
            job.Un_Scheduled__c = false;
            updateJobs.add(job);
        }
    
        if(!updateJobs.isEmpty()) {
            update updateJobs;
        }
    }
}