force-app/main/default/objects/Batch_Flow__c/Batch_Flow__c.object-meta.xml
<CustomObject>
    <label>Batch Flow</label>
    <nameField>
        <label>Batch Flow Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Flows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Flow__c/fields/AsyncApexJobId__c.field-meta.xml
<CustomField>
    <fullName>AsyncApexJobId__c</fullName>
    <label>AsyncApexJobId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Batch_Flow__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Batch_Flow__c/fields/Monitor_Jobs__c.field-meta.xml
<CustomField>
    <fullName>Monitor_Jobs__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Monitor Jobs</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Batch_Flow__c/fields/Next_Job__c.field-meta.xml
<CustomField>
    <fullName>Next_Job__c</fullName>
    <label>Next Job</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Batch_Flow__c/fields/Next_Scheduled_Run__c.field-meta.xml
<CustomField>
    <fullName>Next_Scheduled_Run__c</fullName>
    <label>Next Scheduled Run</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Batch_Flow__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BatchFlow_Config__c/BatchFlow_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>BatchFlow Config</label>
</CustomObject>

force-app/main/default/objects/BatchFlow_Config__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BatchFlowTest.cls
@isTest
private class BatchFlowTest {
    static Batch_Flow__c batchFlow {get;set;}
    static Batch_Flow__c batchFlow2 {get;set;}
    static BatchFlow_Config__c flowConfig {get;set;}

    static testMethod void scheduleBatchFlowDefaults() {
        init();
        Test.StartTest();

        // clear asyncapexjobid
        batchFlow.AsyncApexJobId__c = null;
        update batchFlow;
        system.assert(batchFlow.AsyncApexJobId__c == null);

        //Get the system date and time.
        Datetime dt = DateTime.now().addSeconds(5);
        String sch = String.valueOf( dt.second() ) + ' ' + String.valueOf( dt.minute()   ) + ' ' + String.valueOf( dt.hour() ) + ' '  + String.valueOf( dt.day() ) +  ' ' + String.valueOf( dt.month() ) + ' '  + '? ' + String.valueOf( dt.Year());
        // schedule mgr to run
        BatchFlow batch = new BatchFlow();
        Id cronId = system.schedule('Batch Flow Daemon', sch, batch);
        system.assert(cronId != null);

        Test.StopTest();
    }

    static testMethod void failedJobTrigger() {        
        init();
        batchFlow.Next_Job__c = batchFlow2.Id;
        update batchFlow;

        Test.StartTest();
        // set job to failed status
        batchFlow.Status__c = 'Failed';
        // set next job to null to unschedule the job
        batchFlow.Next_Job__c = null;
        update batchFlow;
        system.assert(batchFlow.Status__c == 'Failed');
        Test.StopTest();
    }

    static void Init() {
        // create config record
        flowConfig = new BatchFlow_Config__c();
        flowConfig.Name = 'Config';
        flowConfig.Monitor_Jobs__c = false;
        flowConfig.Frequency__c = 5;
        insert flowConfig;

        // create 1 active job
        batchFlow = new Batch_Flow__c();
        batchFlow.Name = 'test';
        batchFlow.Apex_Class__c = 'test';
        // setup start and end time for job to make job active
        batchFlow.Active__c = true;
        batchFlow.StartTime__c = system.today();
        batchFlow.EndTime__c = system.today().addDays(2);
        batchFlow.Next_Scheduled_Run__c = system.now().addDays(-1);
        batchFlow.Status__c = 'Started';
        batchFlow.AsyncApexJobId__c = 'test';
        batchFlow.Scope_Size__c = 5;
        insert batchFlow;

        system.assert(batchFlow.Next_Scheduled_Run__c != null);
        system.assert(batchFlow.Status__c != null);
        system.assert(batchFlow.AsyncApexJobId__c != null);


        // create 1 active job
        batchFlow2 = new Batch_Flow__c();
        batchFlow2.Name = 'test';
        batchFlow2.Apex_Class__c = 'test';
        // setup start and end time for job to make job active
        batchFlow.Active__c = true;
        batchFlow2.StartTime__c = system.today();
        batchFlow2.EndTime__c = system.today().addDays(2);
        batchFlow2.Next_Scheduled_Run__c = system.now();
        batchFlow2.Status__c = 'Completed';
        batchFlow2.AsyncApexJobId__c = 'test';
        insert batchFlow2;
    }
}